### PR TITLE
return a dataframe from show_perf_stats

### PR DESCRIPTION
**Pull request by ms32035**

### CODE REVIEW

**Comment by ms32035** [comment]
@stefan-jansen would you mind reviewing/merging?

**Comment by stefan-jansen** [comment]
Addressed by #47.

**Comment by ms32035** [comment]
@stefan-jansen I don't see this being addresses in #47

**Comment by stefan-jansen** [comment]
@ms32035 please see https://github.com/stefan-jansen/pyfolio-reloaded/blob/a013587528a92f0f091f27d34b532430fa859558/src/pyfolio/plotting.py#L545

**Pull request closed without merging**
